subscription Results($path: String!) {
  changeToResult(path: $path) {
    path
    numFailingTests
    numPassingTests
    testResults {
      title
      numPassingAsserts
      status
      failureMessages
      ancestorTitles
      duration
    }
  }
}
