query ItemsQuery($filePath: String!) {
  getStyledComponents(path: $filePath) {
    path
    styledComponents {
      name
      declarations {
        name
        value
        type
      }
    }
  }
}
