declare module "directory-tree";
declare module "micromatch";
declare module "@babel/traverse";
declare module "nanoid";
declare module "read-pkg-up";
declare module "open";
declare module "launch-editor";
declare module "*.json";
declare module "lodash.throttle";
