query EditorInfo {
  editorInfo {
    defaultEditor {
      name
      binary
      id
      isTerminalEditor
      paths
      keywords
    }
    allEditors {
      name
      binary
      id
      isTerminalEditor
      paths
      keywords
    }
  }
}
