subscription {
  changeToSummary {
    numPassedTests
    numFailedTests
    numPassedTestSuites
    numFailedTestSuites
    failedTests
    executingTests
    passingTests
    coverage {
      statement
      function
      branch
      line
    }
    haveCoverageReport
  }
}
